Context = "scanner"
title = "eulabeia config"
RedisDbAddress = "/run/redis-openvas/redis.sock"

[Cert]
defaultKeyFile = "/usr/var/lib/gvm/private/CA/serverkey.pem"
defaultCertFile = "/usr/var/lib/gvm/CA/servercert.pem"
defaultCaFile = "/usr/var/lib/gvm/CA/cacert.pem"

[Connection]
# server = "0.0.0.0:0"
server = "broker:9138"
timeout = 10 # in seconds

[ScannerPreferences]
scanInfoStoreTime = 0 # in hours
maxScan = 0  # 0 = disabled
minFreeMemScanQueue = 0  # 0 = disabled
maxQueuedScans = 0  # 0 = disabled
niceness = 10

[Sensor]
Id = "localhorst"

[Feedservice]
Redis = "/run/redis/redis.sock"

[Director]
StoragePath = "/var/lib/eulabeia/director/storage"
KeyFile = "/var/lib/eulabeia/director/private.key"

[Preferences]
config = "~/.eulabeia/config.toml"
logFile = ""
logLevel = ""
